sudo: required
language: node_js
branches:
  only:
    - master
before_install:
  - curl https://install.meteor.com | /bin/sh
script:
  - npm run lint
  - npm test
  - bash check_for_new_version_number.bash
  - sh publish.sh
